### ISSUE TITLE
live input

### ISSUE THREAD

**Issue by cooliobr** [futzu/SCTE-35-HLS-Sideways#1]
hi, it will work with live ?

**Comment by futzu** [comment]
Yeah, that's what's it's for. 

here's what it does

* it rewrites the master and index.m3u8 files locally , expanding the segments  to the full URIs.
* it gets the pts from the first segment and then just adds durations to track the PTS, 
* if it encounters a DISCONTINUITY tag it parses that segment for pts, in case it has changed.
* When it has an ad break, it splits the CUE-OUT or CUE-IN segment to match the splice point, split segments are stored locally with the new master and index.m3u8 files.
* network traffic is reduced by  99.9999% compared to umzz.
```js

#EXTINF:6.0
https://example.com/0/seg541.ts    <-- expands existing segment URI, but doesn't parse the segments


# start: 3255.733333 cue: 3256.0
#EXTINF:0.266667
./0/a-seg542.ts       <--- When there is a SCTE-35 Cue, it splits the segment at the splice point
                                                                    the split segments are stored on your server.

# start: 3256.0 cue: 3256.0        < -- the second split segment is the where the CUE-OUT starts
#EXT-X-CUE-OUT:13.0
#EXT-X-DISCONTINUITY
#EXTINF:5.466666
./0/b-seg542.ts
# start: 3261.466666 cue: 3269.0
#EXT-X-CUE-OUT-CONT:5.466666/13.0
#EXTINF:6.0
https://example.com/0/seg543.ts     <--- during  the ad break, the segments are not parsed 
# start: 3267.466666 cue: 3269.0
#EXT-X-CUE-OUT-CONT:11.466666/13.0
#EXTINF:1.533334
./0/a-seg544.ts                   <-- split on the CUE-IN splice point      

  
# start: 3269.0 cue: 3269.0      <--- CUE IN on the second split segment     
#EXT-X-CUE-IN
#EXT-X-DISCONTINUITY
#EXTINF:4.199999
./0/b-seg544.ts


# start: 3273.199999 cue: None
#EXTINF:6.0
https://example.com/0/seg545.ts   <--- back to not parsing segments
# start: 3279.199999 cue: None
#EXTINF:6.0
https://example.com/0/seg546.ts
```

Each directory looks like this
```js
 ls 0/
  a-seg542.ts    b-seg542.ts 
  a-seg544.ts   b-seg544.ts  
  index.m3u8 sidecar.txt
```

**Comment by futzu** [comment]
try it out:
python3 -m pip install sideways

**Comment by cooliobr** [comment]
i will try next week, there a exhibition this week here


Att.

Rafael Machado
*HALLO! Midia Group.*




Em sex., 2 de fev. de 2024 às 14:00, Adrian ***@***.***>
escreveu:

**Comment by cooliobr** [comment]
hi, Maybe I'm doing something wrong, in the destination directory it only creates the .m3u8 files, but no .ts files.

**Comment by futzu** [comment]
It should only create ts files for CUE-OUT and CUE-IN. segments. It only does it when it needs to do it. Did you use a sidecar file?
I sometimes forget to do that. I'm about to do another release anyway because it's writing the file names for split segments incorrectly in the index.m3u8 files.

**Comment by cooliobr** [comment]
yes, I use sidecar file, I´m confuse because it is different from umzz or x9k3

**Comment by futzu** [comment]
That is the whole point, it's supposed to be. umzz has trouble keeping all the renditions in sync over a network, that's the problem I'm trying to solve here. I love x9k3 and umzz, but everybody wants to do it over a network, andnobody has the pipes.
If you have the bandwidth, I would absolutely use umzz. umzz is just multi process x9k3, and x9k3 is pretty damn cool, I love it.

**Comment by cooliobr** [comment]
I agree with your train of thought. Since I have plenty of bandwidth and hardware resources, that's the least of my concerns. Additionally, I have access to many GPUs. If you have any projects that require GPU access, I can grant you access to some containers. Just let me know which OS you need.

**Comment by futzu** [comment]
Oh cool, thank you. 
FYI , I got a new release out, works pretty well if you want to try it v0.0.23

**Comment by cooliobr** [comment]
Hi Adrian,
Adrian, I'm confused because the generation of my profiles (renditions) are all allocated in the root folder. However, Sideways creates a directory (0,1,2,3,4) with only the index.m3u8, which returns a 404 error when I try to play it. Am I doing something very wrong? Can you explain to us the best way to use Sideways?


![Captura de Tela 2024-02-14 às 07 51 37](https://github.com/futzu/SCTE-35-HLS-Sideways/assets/4358538/5c75cf59-4295-40cf-9aa4-5ef951d188c5)

**Comment by futzu** [comment]
```smalltalk
a@slow:~$ sideways -i https://c4af3793bf76b33c.mediapackage.us-west-2.amazonaws.com/out/v1/547e1b8d09444666ac810f6f8c78ca82/index.m3u8 -o side -s sidecar.txt
```
```smalltalk
a@slow:~$ ls -hR side
side:
0  1  2  3  master.m3u8

side/0:
a-index2400_00389.ts  a-index2400_01374.ts  b-index2400_01332.ts
a-index2400_00393.ts  a-index2400_01378.ts  b-index2400_01337.ts
a-index2400_01288.ts  b-index2400_00389.ts  b-index2400_01374.ts
a-index2400_01293.ts  b-index2400_00393.ts  b-index2400_01378.ts
a-index2400_01332.ts  b-index2400_01288.ts  index.m3u8
a-index2400_01337.ts  b-index2400_01293.ts  sidecar.txt

side/1:
a-index750_00389.ts  a-index750_01374.ts  b-index750_01332.ts
a-index750_00393.ts  a-index750_01378.ts  b-index750_01337.ts
a-index750_01288.ts  b-index750_00389.ts  b-index750_01374.ts
a-index750_01293.ts  b-index750_00393.ts  b-index750_01378.ts
a-index750_01332.ts  b-index750_01288.ts  index.m3u8
a-index750_01337.ts  b-index750_01293.ts  sidecar.txt

side/2:
a-index5000_00389.ts  a-index5000_01374.ts  b-index5000_01332.ts
a-index5000_00393.ts  a-index5000_01378.ts  b-index5000_01337.ts
a-index5000_01288.ts  b-index5000_00389.ts  b-index5000_01374.ts
a-index5000_01293.ts  b-index5000_00393.ts  b-index5000_01378.ts
a-index5000_01332.ts  b-index5000_01288.ts  index.m3u8
a-index5000_01337.ts  b-index5000_01293.ts  sidecar.txt

side/3:
a-index375_00389.ts  a-index375_01374.ts  b-index375_01332.ts
a-index375_00393.ts  a-index375_01378.ts  b-index375_01337.ts
a-index375_01288.ts  b-index375_00389.ts  b-index375_01374.ts
a-index375_01293.ts  b-index375_00393.ts  b-index375_01378.ts
a-index375_01332.ts  b-index375_01288.ts  index.m3u8
a-index375_01337.ts  b-index375_01293.ts  sidecar.txt
```

**Comment by cooliobr** [comment]
For some reason, even after updating all packages, it's not downloading the .ts files.

![Captura de Tela 2024-02-14 às 20 43 55](https://github.com/futzu/SCTE-35-HLS-Sideways/assets/4358538/c465a6fc-1e32-49e1-adcc-d54bdd121e9e)

**Comment by futzu** [comment]
I explain how this works in the readme.

https://github.com/futzu/SCTE-35-HLS-Sideways#running

The whole point is to not download stuff unless we have to. 
the original segments are reused, the urls are expanded in the new m3u8 files. 


It only downloads segments that have a CUE-IN or CUE-OUT if  there is an iframe closer to the splice point.
* The Splice Point was at  82901.235822 
* index_2_4716287.ts was downloaded and split into a-index_2_4716287.ts,  and b-index_2_4716287.ts 
* a-index_2_4716287.ts ends at 82901.2355822
* b-index_2_4716287.ts starts at 82901.2355822


```smalltalk
...

#EXTINF:2.764178
a-index_2_4716287.ts

# start: 82901.235822 
#EXT-X-CUE-OUT:60.0
#EXT-X-DISCONTINUITY
#EXTINF:3.235822
b-index_2_4716287.ts
...
```

**Comment by cooliobr** [comment]
I found my problem, since I'm using locally, the m3u8 is being rewritten as " ```
# start: 86377.5 
#EXT-X-PROGRAM-DATE-TIME:2024-02-15T10:43:25.348-0300
#EXTINF:6
/usr/share/ffplayout/public/live/FASTY/live-1080p-000079683.ts
# start: 86383.5 
#EXT-X-PROGRAM-DATE-TIME:2024-02-15T10:43:31.348-0300
#EXTINF:6
/usr/share/ffplayout/public/live/FASTY/live-1080p-000079684.ts
# start: 86389.5 
#EXT-X-PROGRAM-DATE-TIME:2024-02-15T10:43:37.348-0300
#EXTINF:6
/usr/share/ffplayout/public/live/FASTY/live-1080p-000079685.ts
# start: 86395.5 
#EXT-X-PROGRAM-DATE-TIME:2024-02-15T10:43:43.348-0300
#EXTINF:6
/usr/share/ffplayout/public/live/FASTY/live-1080p-000079686.ts".

```

And when I'm in the local folder

`[root@8c119e3ad1f8 FASTY]# cat side/0/index.m3u8  
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:79739
#EXT-X-I-FRAMES-ONLY
# start: 86719.5 
#EXT-X-PROGRAM-DATE-TIME:2024-02-15T10:49:07.348-0300
#EXTINF:6
./live-1080p-000079740.ts
# start: 86725.5 
#EXT-X-PROGRAM-DATE-TIME:2024-02-15T10:49:13.348-0300
#EXTINF:6
./live-1080p-000079741.ts
# start: 86731.5 
#EXT-X-PROGRAM-DATE-TIME:2024-02-15T10:49:19.348-0300
#EXTINF:6
./live-1080p-000079742.ts
# start: 86737.5 
#EXT-X-PROGRAM-DATE-TIME:2024-02-15T10:49:25.348-0300
#EXTINF:6
./live-1080p-000079743.ts
# start: 86743.5 
#EXT-X-PROGRAM-DATE-TIME:2024-02-15T10:49:31.348-0300
#EXTINF:6
./live-1080p-000079744.ts` But when I use an address http://......m3u8, it works correctly
